# Generated by Django 5.0.2 on 2024-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_time", models.CharField(max_length=20)),
                ("free_delivery", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
